# Generated by Django 4.1.5 on 2023-01-27 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('navbarProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='web',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='website page'),
        ),
    ]
